server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: Library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true

